./al tests/phase3/backpatch.asc    out.txt
./al tests/phase3/backpatch0.asc    out.txt
./al tests/phase3/backpatch1.asc    out.txt
./al tests/phase3/backpatch2.asc    out.txt
./al tests/phase3/backpatch3.asc    out.txt
./al tests/phase3/test1.asc         out.txt
./al tests/phase3/test2.asc         out.txt
./al tests/phase3/test3.asc         out.txt
./al tests/phase3/test4.asc         out.txt
./al tests/phase3/test5.asc         out.txt
./al tests/phase3/test6.asc         out.txt
./al tests/phase3/test7.asc         out.txt
./al tests/phase3/test8.asc         out.txt
./al tests/phase3/test9.asc         out.txt
./al tests/phase3/test10.asc        out.txt
./al tests/phase3/test11.asc        out.txt
./al tests/phase3/test12.asc        out.txt
./al tests/phase3/test13.asc        out.txt
./al tests/phase3/test14.asc        out.txt
./al tests/phase3/test15.asc        out.txt
./al tests/phase3/vavouris.asc      out.txt
./al tests/phase3/vavouris1.asc     out.txt